/*
	MIT License

	Copyright (c) 2024 RealTimeChris

	Permission is hereby granted, free of charge, to any person obtaining a copy of this
	software and associated documentation files (the "Software"), to deal in the Software
	without restriction, including without limitation the rights to use, copy, modify, merge,
	publish, distribute, sublicense, and/or sell copies of the Software, and to permit
	persons to whom the Software is furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all copies or
	substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
	FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
	OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.
*/
/// https://github.com/RealTimeChris/Json-Performance
#pragma once

#include "common.hpp"

namespace tests {	
	
	static constexpr bnch_swt::string_literal stage_name{ "Json-Performance" };

	static constexpr bnch_swt::stage_config_data config{ .clear_cpu_caches_before_iterations = true,
		.measured_iteration_count															 = measured_iteration_count,
		.max_iteration_count																 = max_iteration_count,
		.max_time_in_s																		 = 10 };

	using benchmark_stage = bnch_swt::benchmark_stage<stage_name, config>;

	std::string make_commit_row(std::string_view label, std::string_view org_repo, std::string_view commit) {
		return std::string("| ") + std::string(label) + ": [" + std::string(commit) + "](https://github.com/" + std::string(org_repo) + "/commit/" + std::string(commit) + ")  \n";
	}

	std::string make_section00(const std::string& os_id, const std::string& os_version, const std::string& compiler_id, const std::string& compiler_version) {
		return std::string("# Json-Performance\nPerformance profiling of JSON libraries (Compiled and run on ") + os_id + " " + os_version + " using the " + compiler_id + " " +
			compiler_version + " compiler).  \n\nLatest Results: (";
	}

	std::string make_section01() {
		return std::string("#### Using the following commits:\n----\n") + make_commit_row("Jsonifier", "RealTimeChris/Jsonifier", JSONIFIER_COMMIT) +
			make_commit_row("Simdjson (On Demand)", "simdjson/simdjson", SIMDJSON_COMMIT);
	}

	std::string make_section02(const auto& cpu_name) {
		std::stringstream stream;
		stream << "\n> > In these tests, we are comparing the 'json structural tape' generated by each of the libraries during their 'stage-1' parsing. You can view the branch "
				  "that was created on the simdjson repo to facilitate this comparison "
				  "[here](https://github.com/RealTimeChris/simdjson/commit/a3a6e2fe9acc5d75a5938127cfec13a7ae9a640e).  ";
		return stream.str();
	}

	struct comparison_context {
		std::vector<uint32_t> indices{};
	};

	template<bnch_swt::string_literal test_name> void execute_test(std::string& newer_string) {
		auto json_data_in = bnch_swt::file_handle::get(json_path.operator std::string() + "/" + test_name.operator std::string() + ".json");
		comparison_context jsonifier_context{};
		jsonifier::jsonifier_core<> jsonifier_parser{};
		jsonifier_parser.parseJsonForComparison<jsonifier::parse_options{ .partialRead = true }>(jsonifier_context, json_data_in);
		comparison_context simdjson_context{};
		simdjson::ondemand::parser simdjson_parser{};
		simdjson_parser.iterate_for_comparison(simdjson_context, simdjson::padded_string_view{ json_data_in });

		newer_string += "\n----\n### " + test_name.operator std::string() + " Structural Comparison\n\n";

		if (jsonifier_context.indices.size() != simdjson_context.indices.size()) {
			std::cout << "Sorry, but there is not an equal number of indices!" << std::endl;
			std::cout << "Jsonifier produced: " << jsonifier_context.indices.size() << std::endl;
			std::cout << "Simdjson produced: " << simdjson_context.indices.size() << std::endl;
			newer_string += "**MISMATCH:** Jsonifier produced " + std::to_string(jsonifier_context.indices.size()) + " structurals, Simdjson produced " +
				std::to_string(simdjson_context.indices.size()) + ".\n\n";
			std::exit(-1);
		} else {
			uint64_t mismatched_count = 0;
			for (uint64_t x = 0; x < jsonifier_context.indices.size(); ++x) {
				if (jsonifier_context.indices[x] != simdjson_context.indices[x]) {
					std::cout << "Sorry, but there is an unequal structural index!" << std::endl;
					std::cout << "At index: " << x << std::endl;
					++mismatched_count;
				}
			}
			std::cout << "All " << jsonifier_context.indices.size() << " structurals match, for test: " << test_name << std::endl;

			if (mismatched_count == 0) {
				newer_string += "All **" + std::to_string(jsonifier_context.indices.size()) + "** structurals match between Jsonifier and Simdjson. ✅\n\n";
			} else {
				newer_string += "**" + std::to_string(mismatched_count) + "** of " + std::to_string(jsonifier_context.indices.size()) + " structurals mismatched. ❌\n\n";
			}
		}
	}

	void test_function() {
		std::string newer_string{ make_section00(static_cast<std::string>(bnch_swt::system_info_data<bnch_swt::benchmark_types::cpu>::os_id),
									  static_cast<std::string>(bnch_swt::system_info_data<bnch_swt::benchmark_types::cpu>::os_version),
									  static_cast<std::string>(bnch_swt::system_info_data<bnch_swt::benchmark_types::cpu>::compiler_id),
									  static_cast<std::string>(bnch_swt::system_info_data<bnch_swt::benchmark_types::cpu>::compiler_version)) +
			bnch_swt::get_time() + ")\n" + make_section01() + static_cast<std::string>(make_section02(bnch_swt::internal::get_device_info<bnch_swt::benchmark_types::cpu>())) };
		execute_test<"Abc (In Order) Partial Test (Minified)">(newer_string);
		execute_test<"Abc (In Order) Partial Test (Prettified)">(newer_string);
		execute_test<"Abc (In Order) Test (Minified)">(newer_string);
		execute_test<"Abc (In Order) Test (Prettified)">(newer_string);
		execute_test<"Abc (Out of Order) Partial Test (Minified)">(newer_string);
		execute_test<"Abc (Out of Order) Partial Test (Prettified)">(newer_string);
		execute_test<"Abc (Out of Order) Test (Minified)">(newer_string);
		execute_test<"Abc (Out of Order) Test (Prettified)">(newer_string);
		execute_test<"Apache Builds Test (Minified)">(newer_string);
		execute_test<"Apache Builds Test (Prettified)">(newer_string);
		execute_test<"Canada Test (Minified)">(newer_string);
		execute_test<"Canada Test (Prettified)">(newer_string);
		execute_test<"CitmCatalog Test (Minified)">(newer_string);
		execute_test<"CitmCatalog Test (Prettified)">(newer_string);
		execute_test<"Discord Test (Minified)">(newer_string);
		execute_test<"Discord Test (Prettified)">(newer_string);
		execute_test<"Github Events Test (Minified)">(newer_string);
		execute_test<"Github Events Test (Prettified)">(newer_string);
		execute_test<"Google Maps Response Test (Minified)">(newer_string);
		execute_test<"Google Maps Response Test (Prettified)">(newer_string);
		execute_test<"Instruments Test (Minified)">(newer_string);
		execute_test<"Instruments Test (Prettified)">(newer_string);
		execute_test<"Marine IK Test (Minified)">(newer_string);
		execute_test<"Marine IK Test (Prettified)">(newer_string);
		execute_test<"Mesh Test (Minified)">(newer_string);
		execute_test<"Mesh Test (Prettified)">(newer_string);
		execute_test<"Random Test (Minified)">(newer_string);
		execute_test<"Random Test (Prettified)">(newer_string);
		execute_test<"Semanticscholar Corpus Test (Minified)">(newer_string);
		execute_test<"Semanticscholar Corpus Test (Prettified)">(newer_string);
		execute_test<"Twitter Partial Test (Minified)">(newer_string);
		execute_test<"Twitter Partial Test (Prettified)">(newer_string);
		execute_test<"Twitter Test (Minified)">(newer_string);
		execute_test<"Twitter Test (Prettified)">(newer_string);
		bnch_swt::file_handle::save_file(static_cast<std::string>(newer_string), read_me_path.operator std::string() + "/" + current_path + ".md");
		auto stage_results = benchmark_stage::get_all_results();
		std::cout << "Md Data: " << newer_string << std::endl;
		bnch_swt::execute_python_script(base_path.operator std::string() + "/GenerateGraphs.py", csv_out_path + "/", graphs_path);
	}
}