name: Build-and-Test

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  Build-MSVC-Windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]

    steps:
    - uses: actions/checkout@v4
      
    - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
        name: PATH
        value: $env:PATH;C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build

    - name: Install Seaborn
      run: |
        pip install seaborn
                
    - name: Configure CMake
      working-directory: ./
      run: |
        cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build the Test
      working-directory: ./Build
      run: |
        cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
        cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: D:/a/Json-Performance/Json-Performance/Install/bin/
      run: |
        ./Json-Performance
      continue-on-error: true

    - name: Commit and push the changes to a temp branch.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      working-directory:  D:/a/Json-Performance/Json-Performance/
      run: |
            git config --global user.email "40668522+RealTimeChris@users.noreply.github.com"
            git config --global user.name "RealTimeChris"
            git checkout -b temp-branch-msvc-windows
            git add . 
            git commit -m "Updates - MSVC-Windows"
            git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/RealTimeChris/Json-Performance.git temp-branch-msvc-windows

  Build-GCC-Ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]

    steps:
    - uses: actions/checkout@v4
     
    - name: Install Seaborn
      run: |
        pip install seaborn
  
    - name: Install the latest gcc compiler.
      working-directory: ./
      run:  |
        sudo apt-get install build-essential
        sudo apt-get install g++-12

    - name: Configure CMake
      working-directory: ./
      run: |
        cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/g++-12

    - name: Build the Test
      working-directory: ./Build
      run: |
        cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
        sudo cmake --install . --config=${{matrix.build_type}}
        sudo chmod +x /home/runner/work/Json-Performance/Json-Performance/Install/bin/Json-Performance

    - name: Run the Test
      working-directory: /home/runner/work/Json-Performance/Json-Performance/Install/bin/
      run: |
        ./Json-Performance
      continue-on-error: true

    - name: Commit and push the changes to a temp branch.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      working-directory: /home/runner/work/Json-Performance/Json-Performance/
      run: |
            sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com"
            sudo git config --global user.name "RealTimeChris"
            sudo git checkout -b temp-branch-gcc-ubuntu
            sudo git add . 
            sudo git commit -m "Updates - GCC-Ubuntu"
            sudo git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/RealTimeChris/Json-Performance.git temp-branch-gcc-ubuntu

  Build-CLANG-Ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest Clang compiler.
      run:  |
        sudo apt update && sudo apt upgrade
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 19

    - name: Install Seaborn
      run: |
        pip install seaborn
                
    - name: Configure CMake
      working-directory: ./
      run: |
        cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-19

    - name: Build the Test
      working-directory: ./Build
      run: |
        cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
        sudo cmake --install . --config=${{matrix.build_type}}
        sudo chmod +x /home/runner/work/Json-Performance/Json-Performance/Install/bin/Json-Performance

    - name: Run the Test
      working-directory: /home/runner/work/Json-Performance/Json-Performance/Install/bin/
      run: |
        ./Json-Performance
      continue-on-error: true
                
    - name: Commit and push the changes to a temp branch.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      working-directory: /home/runner/work/Json-Performance/Json-Performance/
      run: |
            sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com"
            sudo git config --global user.name "RealTimeChris"
            sudo git checkout -b temp-branch-clang-ubuntu
            sudo git add . 
            sudo git commit -m "Updates - CLANG-Ubuntu"
            sudo git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/RealTimeChris/Json-Performance.git temp-branch-clang-ubuntu

  Build-CLANG-MacOS:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest clang compiler.
      run: |
        brew install llvm

    - name: Install Seaborn
      run: |
        pip install seaborn

    - name: Install Nasm.
      run: |
        brew install nasm

    - name: Configure CMake
      working-directory: ./
      run: |
        cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++

    - name: Build the Test
      working-directory: ./Build
      run: |
        cmake --build . --config=${{ matrix.build_type }}

    - name: Install the Test
      working-directory: ./Build
      run: |
        sudo cmake --install . --config=${{ matrix.build_type }}
        sudo chmod +x /Users/runner/work/Json-Performance/Json-Performance/Install/bin/Json-Performance

    - name: Run the Test
      working-directory: /Users/runner/work/Json-Performance/Json-Performance/Install/bin/
      run: |
        ./Json-Performance
      continue-on-error: true

    - name: Commit and push the changes to a temp branch.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      working-directory: /Users/runner/work/Json-Performance/Json-Performance/
      run: |
            sudo git config --global user.email "40668522+RealTimeChris@users.noreply.github.com"
            sudo git config --global user.name "RealTimeChris"
            sudo git checkout -b temp-branch-clang-macos
            sudo git add . 
            sudo git commit -m "Updates - CLANG-MacOS"
            sudo git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/RealTimeChris/Json-Performance.git temp-branch-clang-macos

  Merge-Branches:
    runs-on: ubuntu-latest
    needs:
      - Build-MSVC-Windows
      - Build-GCC-Ubuntu
      - Build-CLANG-Ubuntu
      - Build-CLANG-MacOS

    steps:
    - uses: actions/checkout@v4

    - name: Merge all temporary branches into the main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo git fetch origin
        sudo git checkout main
        sudo git merge origin/temp-branch-msvc-windows --no-ff
        sudo git merge origin/temp-branch-gcc-ubuntu --no-ff
        sudo git merge origin/temp-branch-clang-ubuntu --no-ff
        sudo git merge origin/temp-branch-clang-macos --no-ff
        sudo git push origin main

    - name: Delete temporary branches
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo git push origin --delete temp-branch-msvc-windows
        sudo git push origin --delete temp-branch-gcc-ubuntu
        sudo git push origin --delete temp-branch-clang-ubuntu
        sudo git push origin --delete temp-branch-clang-macos