name: Build-and-Test-CLANG-MacOS

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        clang: [19]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          xcodebuild -version

    - name: Configure CMake
      run: cmake -B build -G Xcode -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DJSONIFIER_TEST="TRUE"

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: /usr/local/bin/
      run: |
            sudo chmod +x ./Json-Performance
            ./Json-Performance
      continue-on-error: true
      