name: Build-and-Test-GCC-Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        gcc: [12]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4
     
    - name: Install Seaborn
      run: |
            pip install seaborn
  
    - name: Install the latest gcc compiler.
      working-directory: ./
      run:  |
            sudo apt-get install build-essential
            sudo apt-get install g++-12

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/g++-12

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}
           sudo chmod +x /usr/local/bin/Json-Performance

    - name: Run the Test
      working-directory: /usr/local/bin/
      run: |
           ./Json-Performance
      continue-on-error: true